from schemas import OrderAnalysis


VALID_PROPERTY_TYPES = {
    "rumah",
    "apartemen",
    "kantor",
    "ruko",
    "villa",
}


def normalize(text: str) -> str:
    return " ".join(text.lower().strip().split())


def canonical_service(service_name: str, service_catalog: dict) -> str | None:
    """Return the catalog name if the extracted service matches exactly."""
    target = normalize(service_name)
    for name in service_catalog:
        if normalize(name) == target:
            return name
    return None


def calculate_pricing(analysis: OrderAnalysis, service_catalog: dict):
    """
    Business rule: price is NEVER generated by AI.
    Python takes the canonical catalog price and multiplies it by quantity.
    """
    rows = []
    grand_total = 0

    for item in analysis.items:
        canonical = canonical_service(item.service_name, service_catalog)
        quantity = item.quantity
        if quantity is not None and not (1 <= quantity <= 100):
            quantity = None

        if canonical is None:
            unit_price = None
            subtotal = None
        else:
            # Unit price is known from the catalog even if quantity is missing.
            unit_price = service_catalog[canonical]
            if quantity is None:
                subtotal = None
            else:
                subtotal = unit_price * quantity
                grand_total += subtotal

        rows.append(
            {
                "Layanan": canonical or item.service_name,
                "Qty": quantity if quantity is not None else "-",
                "Harga Satuan": unit_price,
                "Subtotal": subtotal,
                "Catatan": item.item_note or "-",
            }
        )

    return rows, grand_total


def deterministic_missing_fields(
    analysis: OrderAnalysis,
    service_catalog: dict,
) -> list[str]:
    """
    Deterministic validation. These are operational requirements for this
    cleaning-service demo, not guesses made by Gemini.
    """
    missing: set[str] = set()

    # Rule 1 — service must be in the service catalog and have a quantity.
    if not analysis.items:
        missing.add("layanan")

    for item in analysis.items:
        if canonical_service(item.service_name, service_catalog) is None:
            missing.add("layanan yang tersedia di katalog")
        if item.quantity is None or not (1 <= item.quantity <= 100):
            missing.add("jumlah layanan yang valid")

    # Rule 2 — exact schedule is required.
    if not analysis.service_date:
        missing.add("tanggal layanan")
    if not analysis.service_time:
        missing.add("jam layanan yang pasti")

    # Rule 3 — service method must be confirmed.
    if analysis.fulfillment == "unknown":
        missing.add("metode layanan (onsite/pickup)")

    # Rule 4 — property information is required for the cleaning team.
    if not analysis.property_type:
        missing.add("tipe properti")
    if not analysis.property_detail:
        missing.add("detail properti (mis. jumlah lantai)")

    # Rule 5 — onsite cleaning requires an address.
    if analysis.fulfillment == "onsite" and not analysis.address:
        missing.add("alamat layanan")

    # Rule 5 — property type must be recognizable.
    if analysis.property_type:
        if normalize(analysis.property_type) not in VALID_PROPERTY_TYPES:
            missing.add("tipe properti yang valid")

    return sorted(missing)


def deterministic_risk_flags(
    analysis: OrderAnalysis,
    service_catalog: dict,
) -> list[str]:
    flags = list(analysis.risk_flags)

    if analysis.fulfillment == "unknown":
        flags.append("Metode layanan belum jelas; demo ini berfokus pada layanan onsite.")

    if analysis.property_type:
        if normalize(analysis.property_type) not in VALID_PROPERTY_TYPES:
            flags.append(
                "Tipe properti tidak termasuk pilihan demo: Rumah, Apartemen, Kantor, Ruko, Villa."
            )

    for item in analysis.items:
        if canonical_service(item.service_name, service_catalog) is None:
            flags.append(f"Layanan '{item.service_name}' tidak ditemukan di katalog.")

    # Preserve order while removing duplicates.
    return list(dict.fromkeys(flags))


def order_status(
    analysis: OrderAnalysis,
    service_catalog: dict,
) -> str:
    missing = deterministic_missing_fields(analysis, service_catalog)
    return "READY" if not missing else "NEEDS CONFIRMATION"
